config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :invoices, only: [:index, :new, :create, :edit, :destroy]

  match 'collections/:id', to: 'collections#create', via: [:post], as: :collection_create
  resources :collections, only: [:new, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord

  belongs_to :invoice

  after_create :update_invoice_due_and_collection_amount

  validate :validate_amount

  def self.create_collection_records
    $collection_records.each do |resource|
      inv = Invoice.find_by(reference: resource[:reference])
      if inv.present?
        collection = inv.collections.new(
          amount: resource[:amount].to_i.abs,
          collection_date: resource[:collection_date].to_time
        )
        collection.save
      else
        next
      end
    end
  end

  def update_invoice_due_and_collection_amount
    invoice = self.invoice
    invoice.balance_due -= self.amount
    invoice.total_collection += self.amount
    invoice.save
  end

  def validate_amount
    invoice = self.invoice
    errors.add(:amount, :invalid) if self.amount > invoice.balance_due
  end

end

app/models/invoice.rb
class Invoice < ApplicationRecord

  has_many :collections, dependent: :destroy

  validates :reference, uniqueness: true

  def self.create_invoice_records
    $invoice_records.each do |resource|
      begin
        invoice = Invoice.new(
          reference: resource[:reference],
          invoice_date: resource[:invoice_date].to_time,
          customer: resource[:customer_name],
          brand_manager: resource[:brand_manager],
          narration: resource[:narration],
          amount: resource[:amount],
          balance_due: resource[:amount]
        )
        invoice.save
      rescue Exception => e
        next
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def new
    render 'form'
  end

  def create
    resource_params = params[:collection].permit!
    resource_params[:invoice_id] = params[:id].to_i
    @collection = Collection.new(resource_params)
    respond_to do |format|   
      if @collection.valid?
        @collection.save
        flash.notice = 'Collection was successfully created.'
        format.html { redirect_to invoices_url }   
      else
        format.html { render :form }   
        format.json { render json: @collection.errors, status: :unprocessable_entity }   
      end   
    end
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action do
    @model = params['controller'].classify.constantize
  end

  def index
    @q = @model.ransack(params[:q])
    @invoices = @q.result(distinct: true).page(params[:page] || 1)
    @invoices = @invoices.where("balance_due > ?", 0) if params[:constraints].eql?("pending_bills")
    @invoices = @invoices.where("balance_due = ?", 0) if params[:constraints].eql?("collected_bills")
  end

  def new
    render 'form'
  end

  def create   
    resource_params = params[:invoice].permit!
    resource_params[:balance_due] = resource_params[:amount]
    @invoice = Invoice.new(resource_params)
    respond_to do |format|   
      if @invoice.valid?
        @invoice.save
        flash.notice = 'Invoice was successfully created.'
        format.html { redirect_to invoices_url }   
      else
        format.html { render :form }   
        format.json { render json: @invoice.errors, status: :unprocessable_entity }   
      end   
    end   
  end

  def edit
    @invoice = Invoice.find(params[:id])
    @collections = @invoice.collections
    render 'edit'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <link rel="stylesheet" media="all" href="/assets/application.debug-8a43eeea7df00d2dc5bb7cdd615e57d5eff38da03b2c15864e8b583623b1033e.css" data-turbolinks-track="reload" />
  </head>

  <body>
    <div class="invoice_form">
      <form action="<%= url_for(params.permit!.to_h.slice(:controller, :id).merge(action: 'create')) %>" accept-charset="UTF-8" data-remote="true" method="post">
        <% if @collection.present? and @collection.errors.any? %>   
          <div id="error_explanation">   
            <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this invoice from being saved:</h2>   
        
            <ul>   
            <% @collection.errors.full_messages.each do |message| %>   
              <li><%= message %></li>   
            <% end %>   
            </ul>   
          </div>   
        <% end %>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

        <label for="collection_reference" class="form-label">Reference</label><br>
        <input type="text" class="form-control" id="collection_amount" value="<%= params[:reference] %>" readonly /><br>
      
        <label for="collection_amount" class="form-label">Amount</label><br>
        <input type="number" name="collection[amount]" class="form-control" id="collection_amount" /><br>

        <label for="collection_collection_date" class="form-label">Collection Date</label><br>
        <input type="date" name="collection[collection_date]" class="form-control" id="collection_collection_date" /><br>

        <input type="submit" class="btn btn-primary" name="create" value="Save" data-disable-with="Save" />

        <%= link_to 'Back', invoices_path, class: "btn btn-primary" %>   
      </form>
    </div>
  </body>
</html>

app/views/invoices/edit.html.erb
<body>
  <div class='invoice_details'>
    <p style="color:blue;font-size:120%"><%= @invoice.reference %></p>
    <p style="color:black;font-size:120%">Customer: <%= @invoice.customer %></p>
    <p style="color:black;font-size:120%">Brand manager: <%= @invoice.brand_manager %></p>
    <p style="color:black;font-size:120%">Narration: <%= @invoice.narration %></p>
  </div>
  <div class='container-fluid'>
    <div class='row py-10 px-3'>
      <div class='col-5 col-sm-12'>
        <table id='invoice-table' class="table table-hover">
          <thead  class="thead-light">
            <tr>
              <th>Date</th>
              <th>Event</th>
              <th>Amount</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td><%= @invoice.invoice_date.strftime("%Y-%m-%d") %></td>
              <td>New Invoice</td>
              <td><%= @invoice.amount %></td>
            </tr>
              <% if @collections.any? %>
                <% @collections.each do |collection| %>
                  <tr>
                    <td><%= collection.collection_date.strftime("%Y-%m-%d") %></td>
                    <td>Collection</td>
                    <td><%= collection.amount %></td>
                  </tr>
                <% end %>
              <% end %>
            <tr>
              <td></td>
              <td>Balance due</td>
              <td><%= @invoice.balance_due %></td>
            </tr>
          </tbody>
        </table>
        <br>
        <div class='form_actions'>
          <button type="button" id="addCollection" class="btn btn-primary" onclick="window.location.href='<%= (new_collection_url + '?id=' + @invoice.id.to_s + '&reference=' + @invoice.reference) %>';" >Add Collection</button>
          <%= link_to 'Back', invoices_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</body>
<script>
  var is_bill_collected = <%= @invoice.balance_due == 0 %>;
  if (is_bill_collected){
    document.getElementById("addCollection").disabled = true;
  }
</script>

app/views/invoices/form.html.erb
<!DOCTYPE html>
<html>

  <body>
    <div class="invoice_form">
      <form action="/invoices" accept-charset="UTF-8" data-remote="true" method="post">
        <% if @invoice.present? and @invoice.errors.any? %>   
          <div id="error_explanation">   
            <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>   
        
            <ul>   
            <% @invoice.errors.full_messages.each do |message| %>   
              <li><%= message %></li>   
            <% end %>   
            </ul>   
          </div>
        <% end %>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <label for="invoice_customer" class="form-label">Customer</label>:
        <input type="text" name="invoice[customer]" class="form-control input_box" id="invoice_customer" /><br />

        <label for="invoice_brand_manager" class="form-label">Brand manager</label>:
        <input type="text" name="invoice[brand_manager]" class="form-control input_box" id="invoice_brand_manager" /><br />

        <label for="invoice_invoice_date" class="form-label">Invoice date</label>:
        <input type="date" name="invoice[invoice_date]" class="form-control input_box" id="invoice_invoice_date" /><br />

        <label for="invoice_narration" class="form-label">Narration</label>:
        <input type="text" name="invoice[narration]" class="form-control input_box" id="invoice_narration" /><br />

        <label for="invoice_amount" class="form-label">Amount</label>:
        <input type="number" name="invoice[amount]" class="form-control input_box" id="invoice_amount" /><br />

        <label for="invoice_reference" class="form-label">Reference</label>:
        <input type="text" name="invoice[reference]" class="form-control input_box" id="invoice_reference" /><br />

        <input type="submit" name="resource_save" class="btn btn-primary" value="Save Invoice" data-disable-with="Save Invoice" />

        <%= link_to 'Back', invoices_path, class: "btn btn-primary" %>   
      </form>
    </div>
  </body>
</html>

app/views/invoices/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class='bill_tabs'>
      <div class='application_title'>
        <h3>Action Board</h3>
      </div>
      <div class='bill_actions'>
        <div class='bill_views'>
          <button id="showBills" type="button" class="btn btn-primary">All bills</button>
          <button id="showPendingBills" type="button" class="btn btn-primary">Show pending bills</button>
          <button id="showCollectedBills" type="button" class="btn btn-primary">Show collected bills</button>
        </div>
        <button id="addNewBill" type="button" class="btn btn-primary create-bill">Add a new bill</button>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class='container-fluid'>
      <% if @invoices.total_pages >= 1 %>
        <div class='row py-3 px-3'>
          <div class='col-12 col-sm-12'>
            <table id='invoice-table' class="table table-hover">
              <thead  class="thead-light">
                <tr>
                  <th>Reference</th>
                  <th>Invoice Date</th>
                  <th>Customer</th>
                  <th>Brand manager</th>
                  <th>Narration</th>
                  <th>Amount</th>
                  <th>Total Collection</th>
                  <th>Balance due</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
      
              <tbody>
                <% @invoices.each do |invoice| %>
                  <tr>
                    <td><a href=<%= edit_invoice_url(id: invoice.id) %>><%= invoice.reference %></a></td>
                    <td><%= invoice.invoice_date.strftime("%Y-%m-%d") %></td>
                    <td><%= invoice.customer %></td>
                    <td><%= invoice.brand_manager %></td>
                    <td><%= invoice.narration %></td>
                    <td><%= invoice.amount %></td>
                    <td><%= invoice.total_collection %></td>
                    <td><%= invoice.balance_due %></td>
                    <td>
                      <% if invoice.balance_due == 0 %>
                        <button type="button" id="addCollection" class="btn btn-primary" disabled>Add Collection</button>
                      <% else%>
                        <button type="button" id="addCollection" class="btn btn-primary" onclick="window.location.href='<%= (new_collection_url + '?id=' + invoice.id.to_s + '&reference=' + invoice.reference) %>';" >Add Collection</button>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
          </div>
        </div>
        <%= paginate @invoices %>
      <% end %>
    </div>
  </body>
  <script type="text/javascript">
    document.getElementById("showBills").onclick = function () {
      location.href = "<%= invoices_url %>";
    };
    document.getElementById("addNewBill").onclick = function () {
      location.href = "<%= new_invoice_url %>";
    };
    document.getElementById("showPendingBills").onclick = function () {
      location.href = "<%= invoices_url + "?constraints=pending_bills" %>";
    };
    document.getElementById("showCollectedBills").onclick = function () {
      location.href = "<%= invoices_url + "?constraints=collected_bills" %>";
    };
  </script>
</html>
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/react.html.erb
<%= stylesheet_link_tag 'application' %>
<%
  props = {
    domain: Rails.application.secrets[:apps][:server]
  }
%>
<%= react_component("ReactView", props: props) %>